baseurl = "https://seyahdoo.com"
title = "Bahar Doğan"
defaultContentLanguage = "en"
languageCode = "en"
theme = "gokarna"
enableRobotsTXT = true
[params]
    author = "Bahar Doğan"
    description = "Game Developer / Computer Scientist"
    metaKeywords = ["blog", "developer", "personal"]
    avatarurl = "/images/avatar.jpg"
    avatarSize = "size-l" # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
    accentColor = "#FF4D4D"
    showPostsOnHomePage = "recent"
    footer = "Seyahdoo"
    pygmentsStyle = "monokai"
    socialIcons = [
        {name = "github", url = "https://github.com/seyahdoo/"},
        {name = "linkedin", url = "https://www.linkedin.com/in/seyahdoo/"},
        {name = "instagram", url = "https://instagram.com/kardanbaba/"},
        {name = "discord", url = "https://discord.gg/ZtDFmjXe7w"},
    ]
    customHeadHTML = '''
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-81CYH00FZ7"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
    
            gtag('config', 'G-81CYH00FZ7');
        </script>
    '''
[menu]
    [[menu.main]]
        identifier = "posts"
        url = "/blog/"
        name = "Blog"
        weight = 1
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 3
    [[menu.main]]
        identifier = "hobbies"
        name = "Hobbies"
        url = "/hobbies/"
        weight = 4
    [[menu.main]]
        identifier = "github"
        url = "https://github.com/seyahdoo/"
        weight = 5
        pre = "<span data-feather='github'></span>"
    [[menu.main]]
        identifier = "linkedin"
        url = "https://www.linkedin.com/in/seyahdoo/"
        weight = 6
        pre = "<span data-feather='linkedin'></span>"
    [[menu.main]]
        identifier = "instagram"
        url = "https://instagram.com/kardanbaba/"
        weight = 7
        pre = "<span data-feather='instagram'></span>"
    [[menu.main]]
        identifier = "discord"
        url = "https://discord.gg/ZtDFmjXe7w"
        weight = 8
        pre = "<img class='svg-inject' src='/svg/icons/discord.svg' />"
        
        
        
